version: '3.3'

services:
  rails:
    build: ./rails
    volumes:
      - ./rails/rails_project:/rails_project:delegated
    ports:
      - "3000:3000"
    command: bash -lc "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  vue:
    build: ./vue
    volumes:
      - ./vue/vue_project:/vue_project:delegated
      - /vue/vue_project/node_modules/
    ports:
      - "8080:8080"
    command: bash -lc "npm install && npm run serve"
